import { Trip } from '@/pages/TripHistory';

// Format date for export
const formatDate = (dateString: string) => {
  return new Date(dateString).toLocaleDateString('en-IN', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  });
};

// Export as CSV
export const exportToCSV = (trips: Trip[], filename = 'trip-history') => {
  const headers = ['Date', 'Origin', 'Destination', 'Distance (km)', 'Duration (hrs)', 'Cost (₹)'];
  
  const rows = trips.map(trip => [
    formatDate(trip.date),
    trip.origin,
    trip.destination,
    trip.distance.toString(),
    trip.duration.toString(),
    trip.cost.toString(),
  ]);

  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
  ].join('\n');

  downloadFile(csvContent, `${filename}.csv`, 'text/csv');
};

// Export as PDF (simple HTML-based approach)
export const exportToPDF = (trips: Trip[], filename = 'trip-history') => {
  const totalCost = trips.reduce((sum, trip) => sum + trip.cost, 0);
  const totalDistance = trips.reduce((sum, trip) => sum + trip.distance, 0);
  const totalDuration = trips.reduce((sum, trip) => sum + trip.duration, 0);

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Trip History</title>
      <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #333; }
        h1 { color: #14b8a6; margin-bottom: 8px; }
        .subtitle { color: #666; margin-bottom: 30px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        th { background: #14b8a6; color: white; padding: 12px; text-align: left; }
        td { padding: 12px; border-bottom: 1px solid #eee; }
        tr:hover { background: #f9f9f9; }
        .summary { background: #f5f5f5; padding: 20px; border-radius: 8px; }
        .summary h3 { margin-top: 0; color: #14b8a6; }
        .summary-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; }
        .summary-item { text-align: center; }
        .summary-value { font-size: 24px; font-weight: bold; color: #14b8a6; }
        .summary-label { color: #666; font-size: 14px; }
        .footer { margin-top: 30px; text-align: center; color: #999; font-size: 12px; }
      </style>
    </head>
    <body>
      <h1>🚗 Trip History Report</h1>
      <p class="subtitle">Generated on ${new Date().toLocaleDateString('en-IN', { 
        day: 'numeric', 
        month: 'long', 
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      })}</p>
      
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Route</th>
            <th>Distance</th>
            <th>Duration</th>
            <th>Cost</th>
          </tr>
        </thead>
        <tbody>
          ${trips.map(trip => `
            <tr>
              <td>${formatDate(trip.date)}</td>
              <td>${trip.origin} → ${trip.destination}</td>
              <td>${trip.distance} km</td>
              <td>${trip.duration} hrs</td>
              <td>₹${trip.cost}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <div class="summary">
        <h3>Summary</h3>
        <div class="summary-grid">
          <div class="summary-item">
            <div class="summary-value">${trips.length}</div>
            <div class="summary-label">Total Trips</div>
          </div>
          <div class="summary-item">
            <div class="summary-value">${totalDistance.toFixed(1)} km</div>
            <div class="summary-label">Total Distance</div>
          </div>
          <div class="summary-item">
            <div class="summary-value">₹${totalCost.toLocaleString('en-IN')}</div>
            <div class="summary-label">Total Spent</div>
          </div>
        </div>
      </div>

      <div class="footer">
        <p>Generated by TripMate • Fuel Prices based on your selected city</p>
      </div>
    </body>
    </html>
  `;

  // Open in new window for print
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.onload = () => {
      printWindow.print();
    };
  }
};

// Helper to download file
const downloadFile = (content: string, filename: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
